# Generated by Django 5.0 on 2023-12-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='', max_length=1500),
            preserve_default=False,
        ),
    ]
