# Generated by Django 5.0 on 2023-12-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_slig_alter_job_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='slig',
            new_name='slug',
        ),
    ]
