# Generated by Django 5.0 on 2023-12-16 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_job_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Category',
            new_name='category',
        ),
    ]
